  name: build and deploy leasing
  on:
    push:
      branches: [ "main", "dev" ]

  jobs:
    build-deploy:
      name: build and deploy leasing
      runs-on: ubuntu-22.04
      steps:
        - name: checkout code
          uses: actions/checkout@v3

        - name: setup jdk 21
          uses: actions/setup-java@v3
          with:
            distribution: 'corretto'
            java-version: 21

        - name: build the app
          env:
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
            POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            HOST: ${{ secrets.HOST }}
            JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
            ACCOUNT_ACCESS_KEY_FROM_AWS: ${{ secrets.ACCOUNT_ACCESS_KEY_FROM_AWS }}
            ACCOUNT_SECRET_KEY_FROM_AWS: ${{ secrets.ACCOUNT_SECRET_KEY_FROM_AWS }}
            S3_CONFIGURED_REGION_FROM_AWS: ${{ secrets.S3_CONFIGURED_REGION_FROM_AWS }}
            S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
            S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
            MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
            MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
            MINIO_BUCKET_NAME: ${{ secrets.MINIO_BUCKET_NAME }}
            MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
          run: mvn clean -DskipTests -B package --file pom.xml

        - name: build the docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            dockerfile: Dockerfile
            push: false
            tags: ${{ secrets.DOCKER_REGISTRY_HOST }}/leasing:latest

        - name: login to private registry
          uses: docker/login-action@v3
          with:
            registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
            username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
            password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

        - name: push the docker image to docker registry
          uses: docker/build-push-action@v5
          with:
            context: .
            dockerfile: Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_REGISTRY_HOST }}/leasing:latest
            secrets: |
              "SERVER_PORT=${{ secrets.SERVER_PORT }}"
              "POSTGRES_URL=${{ secrets.POSTGRES_URL }}"
              "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}"
              "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
              "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
              "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
              "HOST=${{ secrets.HOST }}"
              "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}"
              "ACCOUNT_ACCESS_KEY_FROM_AWS=${{ secrets.ACCOUNT_ACCESS_KEY_FROM_AWS }}"
              "ACCOUNT_SECRET_KEY_FROM_AWS=${{ secrets.ACCOUNT_SECRET_KEY_FROM_AWS }}"
              "S3_CONFIGURED_REGION_FROM_AWS=${{ secrets.S3_CONFIGURED_REGION_FROM_AWS }}"
              "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}"
              "S3_ENDPOINT=${{ secrets.S3_ENDPOINT }}"
              "MINIO_ACCESS_KEY=${{ secrets.MINIO_ACCESS_KEY }}"
              "MINIO_SECRET_KEY=${{ secrets.MINIO_SECRET_KEY }}"
              "MINIO_BUCKET_NAME=${{ secrets.MINIO_BUCKET_NAME }}"
              "MINIO_ENDPOINT=${{ secrets.MINIO_ENDPOINT }}"

        - name: Deploy to VPS
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.VPS_IP }}
            username: ${{ secrets.VPS_USER }}
            password: ${{ secrets.VPS_PASSWORD }}
            script: |
              cd /opt/docker/leasing-backend
              docker compose down leasing
              docker compose up -d --build leasing
